name: node-go-labs

services:
  node:
    build: ./node
    container_name: labs-license-node
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"

  go:
    build: ./go
    container_name: labs-license-go
    ports:
      - "8080:8080"
    environment:
      PORT: "8080"
